Feature: Google Sign In Functionality Test 


Scenario: Sign In Test 


Given that I Open google chrome and launch the application to run tests	

When User runs the sign in test to check the sign in functionality			

Then Reset the test for Learn more link Test

Then Reset the test for Create New Account Test

Then Reset the test for Forgot Password link Test




  
# Please note below are the login credentails to login.
# Username: tt5235783
# Password: !!Password123

#
#TestEmail for account Creation: testemail7-27e950@inbox.mailtrap.io
#
#
