Feature: Reset functionality on login page of Application 


Scenario: Verification of Reset button 


Given that I Open google chrome and launch the application to run tests	

When User runs the sign in test to check the sign in functionality			

Then Reset the test for Learn more link Test

Then Reset the test for Create New Account Test

Then Reset the test for Forgot Password link Test





# Please note below are the login credentails to login.
# Username: tt5235783
# Password: !!Password123

#
#TestEmail for accounnt Creation: testemail-27e950@inbox.mailtrap.io
#
#
